### ISSUE TITLE
Test "DetectionHaarDetect32fpAutoTest" crash with heap-buffer-overflow if ASAN is enabled.

### ISSUE THREAD

**Issue by ilue** [ermig1979/Simd#72]
OS: Ubuntu 16.04.5 amd64
Compiler: GCC 5.4.0
CXXFLAGS: -fsanitize=address -O3 -DNDEBUG 

```
[139743213582208] INFO: DetectionHaarDetect32fpAutoTest is started :
[139743213582208] INFO: Test Simd::Base::DetectionHaarDetect32fp[0] & SimdDetectionHaarDetect32fp[0] for size [1920,1080].
=================================================================
==28502==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61300000cae0 at pc 0x000000894383 bp 0x7ffe1a0d1df0 sp 0x7ffe1a0d1de0
READ of size 4 at 0x61300000cae0 thread T0
    #0 0x894382 in Simd::Base::Detect32f(Simd::Detection::HidHaarCascade const&, unsigned long, int, float) (/home/juli/library/Simd/prj/cmake/Test+0x894382)
    #1 0xaf3c4f in Simd::Avx2::Detect32f(Simd::Detection::HidHaarCascade const&, unsigned long, float __vector(8) const&, long long __vector(4)&) (/home/juli/library/Simd/prj/cmake/Test+0xaf3c4f)
    #2 0xaf4582 in Simd::Avx2::DetectionHaarDetect32fp(Simd::Detection::HidHaarCascade const&, Simd::View<Simd::Allocator> const&, Simd::Rectangle<long> const&, Simd::View<Simd::Allocator>&) (/home/juli/library/Simd/prj/cmake/Test+0xaf4582)
    #3 0xaf5338 in Simd::Avx2::DetectionHaarDetect32fp(void const*, unsigned char const*, unsigned long, long, long, long, long, unsigned char*, unsigned long) (/home/juli/library/Simd/prj/cmake/Test+0xaf5338)
    #4 0x6a2c97 in Test::DetectionDetectAutoTest(void const*, int, int, int, int, Test::(anonymous namespace)::FuncD const&, Test::(anonymous namespace)::FuncD const&) (/home/juli/library/Simd/prj/cmake/Test+0x6a2c97)
    #5 0x6a3d05 in Test::DetectionDetectAutoTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, Test::(anonymous namespace)::FuncD const&, Test::(anonymous namespace)::FuncD const&) (/home/juli/library/Simd/prj/cmake/Test+0x6a3d05)
    #6 0x6a4216 in Test::DetectionDetectAutoTest(int, int, int, Test::(anonymous namespace)::FuncD const&, Test::(anonymous namespace)::FuncD const&) (/home/juli/library/Simd/prj/cmake/Test+0x6a4216)
    #7 0x6a481b in Test::DetectionHaarDetect32fpAutoTest() (/home/juli/library/Simd/prj/cmake/Test+0x6a481b)
    #8 0x79a943 in Test::Task::Run() (/home/juli/library/Simd/prj/cmake/Test+0x79a943)
    #9 0x7988ff in Test::MakeAutoTests(std::vector<Test::Group, std::allocator<Test::Group> > const&, Test::Options const&) (/home/juli/library/Simd/prj/cmake/Test+0x7988ff)
    #10 0x46e93e in main (/home/juli/library/Simd/prj/cmake/Test+0x46e93e)
    #11 0x7f187e9e282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #12 0x47b0c8 in _start (/home/juli/library/Simd/prj/cmake/Test+0x47b0c8)

0x61300000cae0 is located 0 bytes to the right of 352-byte region [0x61300000c980,0x61300000cae0)
allocated by thread T0 here:
    #0 0x7f187f8e3532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x8ab1c6 in std::vector<Simd::Detection::HidHaarStage, std::allocator<Simd::Detection::HidHaarStage> >::_M_default_append(unsigned long) (/home/juli/library/Simd/prj/cmake/Test+0x8ab1c6)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 Simd::Base::Detect32f(Simd::Detection::HidHaarCascade const&, unsigned long, int, float)
Shadow bytes around the buggy address:
  0x0c267fff9900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9910: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9920: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c267fff9930: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff9940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c267fff9950: 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa
  0x0c267fff9960: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c267fff9970: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c267fff9980: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c267fff9990: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
  0x0c267fff99a0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==28502==ABORTING
```

**Comment by ermig1979** [comment]
Thank you for bug report. Unfortunately I can't reproduce the bug.
